[alembic]
script_location = /app/backend/alembic
prepend_sys_path = .
timezone = UTC

[loggers]
keys = root,sqlalchemy,alembic
handlers =
qualname = %(qualname)s

[handlers]
keys =

[formatters]
keys =

[metadata]
target_database_url = %(DATABASE_URL)s

[other]
sqlalchemy.url = %(DATABASE_URL)s

